apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: color-simulation
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: color-simulation
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: color-simulation-0.1.0
  name: color-simulation
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: color-simulation
      app.kubernetes.io/name: color-simulation
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: color-simulation
        app.kubernetes.io/name: color-simulation
    spec:
      containers:
        - image: nginx:1.16.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: color-simulation
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: {}
          securityContext: {}
      securityContext: {}
      serviceAccountName: color-simulation